{"name": "test_vwo_login_positive", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Dashboard' in 'Login - VWO'\n +  where 'Login - VWO' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"32718e95cdc2817b132fc4849e8017e9\")>.title", "trace": "self = <test_vwologin_pom2.TestLogin object at 0x0000020D24AD52B0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"32718e95cdc2817b132fc4849e8017e9\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#1 --> VWO App Positive Test Case\")\n    @pytest.mark.usefixtures(\"setup\")\n    def test_vwo_login_positive(self, setup):\n        driver = setup\n        driver.get(self.base_url) # -->Optional to import from conftest\n        loginPage = LoginPage(driver)\n        loginPage.login_to_vwo(user=self.username, pwd=self.password)\n        time.sleep(2)\n    \n>       assert \"Dashboard\" in driver.title\nE       assert 'Dashboard' in 'Login - VWO'\nE        +  where 'Login - VWO' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"32718e95cdc2817b132fc4849e8017e9\")>.title\n\ntest_vwologin_pom2.py:34: AssertionError"}, "start": 1712056199360, "stop": 1712056222399, "uuid": "fa50df2f-3591-466f-9de6-2af07e3fb861", "historyId": "ed13bfa4db684fbdc1440ee9bc3b2995", "testCaseId": "ed13bfa4db684fbdc1440ee9bc3b2995", "fullName": "tests.vwoLoginTests.pom.test_vwologin_pom2.TestLogin#test_vwo_login_positive", "labels": [{"name": "feature", "value": "TC#1 --> VWO App Positive Test Case"}, {"name": "epic", "value": "VWO Login Test"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.vwoLoginTests.pom"}, {"name": "suite", "value": "test_vwologin_pom2"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-T73FDRD"}, {"name": "thread", "value": "13336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.pom.test_vwologin_pom2"}]}